export const deviceRows = [
  {
    id: 1,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 2,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 3,
    name: "Device Name GZ00-01",
    protection: "error",
    connection: "Offline",
    backup: "Oct 25",
  },
  {
    id: 4,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 5,
    name: "Device Name GZ00-01",
    protection: "error",
    connection: "Offline",
    backup: "Oct 25",
  },
  {
    id: 6,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 7,
    name: "Device Name GZ00-01",
    protection: "warning",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 8,
    name: "Device Name GZ00-01",
    protection: "warning",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 9,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Offline",
    backup: "Oct 25",
  },
  {
    id: 10,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 11,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 12,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 13,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 14,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 15,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 16,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 17,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 18,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 19,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
  {
    id: 20,
    name: "Device Name GZ00-01",
    protection: "Ok",
    connection: "Online",
    backup: "Oct 25",
  },
];
export const deviceSoft = [
  {
    id: 1,
    name: "Logos presentation.png",
    tag: "no tag",
    size: "1.23 mb",
    last_modified: "24.02.2022",
  },
  {
    id: 2,
    name: "Company kit.fig",
    tag: "UI Kits",
    size: "39.18 mb",
    last_modified: "23.02.2022",
  },
  {
    id: 3,
    name: "Redesign process.mp4",
    tag: "Design Guides",
    size: "2.72 gb",
    last_modified: "23.02.2022",
  },
  {
    id: 4,
    name: "Avatar",
    tag: "no tag",
    size: "0.87 mb",
    last_modified: "21.02.2022",
  },
  {
    id: 5,
    name: "Ongoing works.xls",
    tag: "University",
    size: "0.29 mb",
    last_modified: "19.02.2022",
  },
  {
    id: 6,
    name: "Presentation.pdf",
    tag: "University",
    size: "56.27 mb",
    last_modified: "17.02.2022",
  },
  {
    id: 7,
    name: "Design workflow.doc",
    tag: "Design Guides",
    size: "1.83 mb",
    last_modified: "17.02.2022",
  },
  {
    id: 8,
    name: "Material.sketch",
    tag: "UI Kits",
    size: "148.91 mb",
    last_modified: "04.02.2022",
  },
];
